server:
  port: 8080
logging:
  level:
    org:
      hibernate:
        SQL: debug
#      springframework: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blackcofferdb
    username: root
    password: Sai369uy@
    driverClassname: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        ddl-auto: update

  batch:
    job:
      enabled: false
    initialize-schema: ALWAYS
    table-prefix: BATCH_
    initializer:
          enabled: false
